spring.application.name=erp

# Conexão com o Neon (com o prefixo jdbc: obrigatorio)
spring.datasource.url=jdbc:postgresql://ep-bold-darkness-acynchcw-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4MZK9UBGdrIo
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true